### ISSUE TITLE
Install instructions are not clear

### ISSUE THREAD

**Issue by imbalu007** [princeton-nlp/AutoCompressors#12]
Hi,
I find the following missing from the install instructions
1. How do I install autocompressors package?
2. What should I install to just perform inference (i.e., obtain soft prompts for a given prompt)?
3. How can I run (2) without flash-attention?

**Comment by CodeCreator** [comment]
Thanks! I've clarified the [installation instructions](https://github.com/princeton-nlp/AutoCompressors?tab=readme-ov-file#install) in the README. The general outline is to clone the repo, install dependencies and run the example inference code in the README. Unfortunately, the Llama code requires flash-attention (and there seems to be a performance gap when training the model with flash-attention and running inference without it). The OPT AutoCompressor does not use flash attention by default.

**Comment by CodeCreator** [comment]
Closing this to due to inactivity -- feel free to re-open!
