### ISSUE TITLE
RuntimeError: FlashAttention only support fp16 and bf16 data type

### ISSUE THREAD

**Issue by stdKonjac** [princeton-nlp/AutoCompressors#15]
Hi,
Thanks for the great work! I am facing a bug and hope you to help me :) @CodeCreator 
When I ran 'bash/train_llama.sh', I got the same error as https://github.com/princeton-nlp/AutoCompressors/issues/13.
After trying the solution, the code stuck with another error: 
**RuntimeError: FlashAttention only support fp16 and bf16 data type**
It seems I should upgrade my transformers version, but I will face issue https://github.com/princeton-nlp/AutoCompressors/issues/13 again, how could I solve it? 
Or could you give a compatible transformers version?

**Comment by stdKonjac** [comment]
After I upgrade my transformers version to 4.35.0, and manually set `do_grad_scaling=False`, the same error occurs.

**Comment by stdKonjac** [comment]
I believe a possible reason is that the FlashRotaryEmbedding set `pos_idx_in_fp32=True` by default, therefore the `q` and `kv` are cast to torch.float32 before feeding into flash_attn_kvpacked_func.
I fixed this issue by explicitly casting `q` and `kv` to torch.bfloat16.

**Comment by CodeCreator** [comment]
Hi! Thanks for finding this issue, which I didn't catch this during the refactoring of `auto_compressor.py`. 

I think your solution sounds good! I have also fixed this now in commit 316d80003d560b87dbbada12128e09eae9d3caef by casting the input variables to the same as the input embeddings dtype (as was the case before the refactoring)
