### ISSUE TITLE
Reduce the number of summary vectors

### ISSUE THREAD

**Issue by rahulseetharaman** [princeton-nlp/AutoCompressors#18]
Hi, is it possible to reduce the number of summary vectors to less than 15 tokens ? I am just curious, if you have tried the number of summary vectors to be in this ballpark and if it works effectively. I did try using a subarray of summary vectors as follows, 

```
generation_with_summary_vecs = model.generate(prompt_tokens, do_sample=False, softprompt=summary_vectors[:, :10, :], max_new_tokens=12)[0]

```

But this gives very random answers. Is there a way to have only reduced summary vectors for the same ?

**Comment by CodeCreator** [comment]
Once the AutoCompressor is trained, you should not change the number of summary vectors if you want to preserve the model quality. Reducing the number of summary vectors would unfortunately require retraining the model.

**Comment by CodeCreator** [comment]
Closing this for now -- Please re-open if you have any more questions!
