### ISSUE TITLE
Question about the data preprocessing

### ISSUE THREAD

**Issue by hxs91** [princeton-nlp/AutoCompressors#19]
Hi, thanks again for your great work, I am reading the source code about AutoCompressor and I have a small question about the preprocessing procedure. Acoording to the code:

> 
    # Main data processing function that will concatenate all texts from our dataset and generate chunks of block_size.
    def group_texts(examples):
      # Concatenate all texts.
      concatenated_examples = {k: list(chain(*examples[k])) for k in examples.keys()}
      total_length = len(concatenated_examples[list(examples.keys())[0]])
      # We drop the small remainder, we could add padding if the model supported it instead of this drop, you can
      # customize this part to your needs.
      if total_length >= block_size:
          total_length = (total_length // block_size) * block_size
      # Split by chunks of max_len.
      result = {
          k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
          for k, t in concatenated_examples.items()
      }
      result["labels"] = result["input_ids"].copy()
      return result

If I am understanding correctly, this function will concatenate texts from **different** docs firstly, and chunk the concatenated text according to `block_size` (maybe 6144 for princeton-nlp/AutoCompressor-Llama-2-7b-6k? this argument is not defined in the released code). We can get text of arbitrary length by this way, which is great for earning long text input, but it also ignores the independence of **different** documents, does it hurt the performance? Thanks.

**Comment by CodeCreator** [comment]
Hi @hxs91 -- apologies for the confusion. Essentially, the `group_texts` function is legacy code in our code base, that we didn't make use in the experiments of the paper. I agree that concatenating different documents would likely hurt performance.

Instead, we preprocessed and tokenized the datasets before training and only included *full documents* in these datasets, e.g., the [train script](https://github.com/princeton-nlp/AutoCompressors/blob/main/run/train_llama.sh#L102) here uses a tokenized dataset, which we uploaded to huggingface hub [awettig/RedPajama-combined-15B-6K-llama](https://huggingface.co/datasets/awettig/RedPajama-combined-15B-6K-llama).
