### ISSUE TITLE
Timeline for Release of Code and Pre-Trained Models

### ISSUE THREAD

**Issue by mpoemsl** [princeton-nlp/AutoCompressors#2]
The paper says 
```
Our code and pre-trained models are publicly available at https://github.com/princeton-nlp/AutoCompressors.
```

Right now, that doesn't seem to be the case. Is there a timeline for this?

**Comment by CodeCreator** [comment]
I am sorry for the delay. Unfortunately, we need to prioritize working on the EMNLP deadline at the moment, but will release the code by June 25 at the latest.

**Comment by mpoemsl** [comment]
That makes sense! Thanks for getting back to me.
