### ISSUE TITLE
Your shared model trained on LLAMA2 is not trained on Lora, It's full-finetuned model.

### ISSUE THREAD

**Issue by jason9693** [princeton-nlp/AutoCompressors#25]
In you paper,
You said llama2 was trained on LLAMA with fewer parameters,
But your shared model (princeton-nlp/AutoCompressor-Llama-2-7b-6k) seems just full fine-tuned model.
https://huggingface.co/princeton-nlp/AutoCompressor-Llama-2-7b-6k/tree/main

If the models is lora-trained, It must be use PEFT library, 
but the that model is not using PEFT, just loaded on only transformers library.

Can you explain about this? 

<img width="484" alt="screenshot" src="https://github.com/user-attachments/assets/2963ec30-0a1c-4270-bef0-74041a567977">

**Comment by CodeCreator** [comment]
We merge the LoRA weights into the main model at the end of training and before uploading to make it easier for folks to use the model without installing PEFT. See the method [here](https://huggingface.co/docs/peft/main/en/package_reference/lora#peft.LoraModel.merge_and_unload).
