### ISSUE TITLE
Does Auto-Compressors support newer base model like LLama-3 or Qwen-2.5?

### ISSUE THREAD

**Issue by RewindL** [princeton-nlp/AutoCompressors#28]
I have tried to train with newer base model LLama-3-3B, and upgrade dependent libraries like transformers, accelerate and so on. But still fails to train.

**Comment by CodeCreator** [comment]
Hey! We built this library for an old version of transformers and we do not have the bandwidth to keep it up-to-date with every new huggingface version and model architecture. If you figure out which changes are necessary to support Llama-3, please open a pull request!

**Comment by RewindL** [comment]
> Hey! We built this library for an old version of transformers and we do not have the bandwidth to keep it up-to-date with every new huggingface version and model architecture. If you figure out which changes are necessary to support Llama-3, please open a pull request!

Thanks for replying. Have a good day.
