### ISSUE TITLE
Follow-up on Code Release Timeline

### ISSUE THREAD

**Issue by mpoemsl** [princeton-nlp/AutoCompressors#3]
I just wanted to follow up on #2. There, @CodeCreator said the code would be released by June 25th at the latest. Is there a new timeline?

**Comment by CodeCreator** [comment]
We're planning for EOD today. Thank you for your patience!

**Comment by mpoemsl** [comment]
Perfect, thank you very much!

**Comment by CodeCreator** [comment]
I've just pushed the first version of the public code. We cleaned the codebase up quite a bit, but we will add more documentation in the next few days. We will also work on releasing our trained models on huggingface hub.

Feel free to send any questions or suggestions you have regarding the code!

**Comment by mpoemsl** [comment]
Thank you very much! I'll have a look.
