### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by xuguohai** [princeton-nlp/AutoCompressors#6]
Can you help me how to conduct experiments using a single NVIDIA A100 80GB GPU?

I meet the problem of "CUDA out of memory." 

My environments:
GPU: NVIDIA A100 80GB GPU   cuda11.7
torch version: 1.13.1 

I have set total batch_size=1, but also out of memory.

Is  there anything that needs to be modified in your `train.sh`?

**Comment by CodeCreator** [comment]
I just pushed the code for training with flash attention, which lowers the GPU memory requirements for training substantially. You can activate this by adding the flag `--fast_attention` when running `train.sh`.

Note that we use `torch.nn.functional.scaled_dot_product_attention` which is still experimental and requires installing the preview version of pytorch. We have also found some issues when using this with `use_cache=True`, so we recommend only using this during training.

Let me know if you encounter any other issues.

**Comment by Patrick-Ni** [comment]
``fast_attention`` doesn't work: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

**Comment by CodeCreator** [comment]
Hmm, are you using this code during evaluation with a `device_map`? 

In training with normal DDP, it should never happen that tensors will be on two different GPUs.
