### ISSUE TITLE
Summary Vector Failures and Incomplete Answers with Numerical Contexts

### ISSUE THREAD

**Issue by iseesaw** [princeton-nlp/AutoCompressors#7]
Hello! Thanks for your impressive works.
I have been exploring this work and ran into some issues while using the example provided with the model princeton-nlp/AutoCompressor-2.7b-6k. It seems that the summary vector approach is not functioning as expected, particularly when the context involves numerical information.

Issues Encountered:
1. Summary vector handling with questions containing numbers: When using the summary vectors, the model fails to generate correct answers for questions that contain numerical information. For example, in the provided cases, the model produces incomplete answers with truncated numbers (e.g., "19" instead of "1973" for the birth year and graduation year of Joe Biden).

2. Incomplete answers: The model also demonstrates an inability to generate full answers in some cases. Instead, it generates truncated responses, cutting off crucial information (e.g., "the" instead of completing the phrase "the presidency").

Example Cases:
- The birth year of Joe Biden is "19 (Expected: "1942")
- Joe Biden graduated from the University of Delaware in the year "19 (Expected: "1965")
- He earned his law degree from Syracuse University College of Law in "1973 (Expected: "1968")
- Joe Biden served as the United States Senator from Delaware for six terms, from "1973 (Expected: "1973 to 2009")
- Biden campaigned for the presidency in "the (Expected: "the 2020 elections")
- He was inaugurated as the 46th President of the United States on "In (Expected: "In January 20, 2021")

It's crucial to address these issues, as they significantly impact the model's ability to provide accurate and complete answers, particularly in scenarios involving numeric contexts. I would appreciate any insights or guidance on resolving these problems to enhance the model's performance in handling such cases.

**Comment by iseesaw** [comment]
I investigated the issue further, and it appears that the problem lies in the next token generation for incomplete answers. Even when using the model.generate method, I still encounter challenges in obtaining accurate answers.

Here are the cases with their respective responses:

1. Next token w/ summary vectors:
   The birth year of Joe Biden is "19
   Response w/ summary vectors:
   The birth year of Joe Biden is "1943."
   Next token w/o context:
   The birth year of Joe Biden is "19

2. Next token w/ summary vectors:
   Joe Biden graduated from the University of Delaware in the year "19
   Response w/ summary vectors:
   Joe Biden graduated from the University of Delaware in the year "1947, the year of the Korean War."
   Next token w/o context:
   Joe Biden graduated from the University of Delaware in the year "19

3. Next token w/ summary vectors:
   He earned his law degree from Syracuse University College of Law in "the
   Response w/ summary vectors:
   He earned his law degree from Syracuse University College of Law in "the old days," before the advent of modern technology.
   Next token w/o context:
   He earned his law degree from Syracuse University College of Law in "the

4. Next token w/ summary vectors:
   Joe Biden served as the United States Senator from Delaware for six terms, from "the
   Response w/ summary vectors:
   Joe Biden served as the United States Senator from Delaware for six terms, from "the day I was born."
   Next token w/o context:
   Joe Biden served as the United States Senator from Delaware for six terms, from "the

5. Next token w/ summary vectors:
   Biden campaigned for the presidency in "the
   Response w/ summary vectors:
   Biden campaigned for the presidency in "the most diverse field in history," and he won the Democratic nomination.
   Next token w/o context:
   Biden campaigned for the presidency in "the

6. Next token w/ summary vectors:
   He was inaugurated as the 46th President of the United States on "In
   Response w/ summary vectors:
   He was inaugurated as the 46th President of the United States on "this day, January 20, 2021."
   Next token w/o context:
   He was inaugurated as the 46th President of the United States on "this

As evident from the responses, while some answers have improved, there are still inaccuracies and missing information. The model-generated responses are often incomplete or contain irrelevant details.

I believe addressing this issue is crucial to enhance the model's performance in generating accurate and comprehensive answers across various contexts, especially when dealing with numerical information. I appreciate any insights or assistance you can provide in resolving this matter. Thank you!

**Comment by CodeCreator** [comment]
Hi, thanks for playing around with the model! I will take a look at this in the coming days, but note that

1. `.generate()` might result in unexpected behaviour as the order of the past-key-values and the softprompt gets mixed up. I will work on a fix for this.
2. The models are not instruction fine-tuned and will not have impressive zero-shot QA performance.

I will report back!

**Comment by qcwthu** [comment]
> Hi, thanks for playing around with the model! I will take a look at this in the coming days, but note that
> 
> 1. `.generate()` might result in unexpected behaviour as the order of the past-key-values and the softprompt gets mixed up. I will work on a fix for this.
> 2. The models are not instruction fine-tuned and will not have impressive zero-shot QA performance.
> 
> I will report back!

Hi, Thanks for your great work! May I ask when will you release the fix for generate() function?

**Comment by CodeCreator** [comment]
@iseesaw @qcwthu It took a while to come up with a clean implementation, but please check out the updated repo that now should support .generate().
